export const START_GETTING_MEASUREMENTS = 'START_GETTING_MEASUREMENTS';
export const STOP_GETTING_MEASUREMENTS = 'STOP_GETTING_MEASUREMENTS';
export const MEASUREMETS_CONNECTED = 'MEASUREMETS_CONNECTED';
export const MEASUREMETS_DISCONNECTED = 'MEASUREMETS_DISCONNECTED';
export const MEASUREMENT_RECEIVED = 'MEASUREMENT_RECEIVED';
export const MEASUREMENT_FAILED = 'MEASUREMENT_FAILED';